name = "r2ls"
main = "r2ls.js"
compatibility_date = "2022-11-20"

## specified via CLOUDFLARE_ACCOUNT_ID env var
# account_id = ""

[[r2_buckets]]
binding = 'R2BUCKET'
bucket_name = 'video'
preview_bucket_name = 'video'

